KalmanFilter:
  dt: 0.05
  n: 6
  m: 2
  # n x n
  A: [1, 0, 0.05, 0, 0.00125, 0, 
      0, 1, 0, 0.05, 0, 0.00125, 
      0, 0, 1, 0, 0.05, 0,
      0, 0, 0, 1, 0, 0.05,
      0, 0, 0, 0, 1, 0,
      0, 0, 0, 0, 0, 1]
  # m x n
  C: [1, 0, 0, 0, 0, 0, 
      0, 1, 0, 0, 0, 0]
  # n x n
  Q: [0.05, 0, 0, 0, 0, 0, 
      0, 0.05, 0, 0, 0, 0, 
      0, 0, 0.05, 0, 0, 0,
      0, 0, 0, 0.05, 0, 0,
      0, 0, 0, 0, 0.05, 0,
      0, 0, 0, 0, 0, 0.05]
  # m x m
  R: [0.012, 0,
      0, 0.012]
  # n x n
  P: [1, 0, 0, 0, 0, 0, 
      0, 1, 0, 0, 0, 0, 
      0, 0, 1, 0, 0, 0,
      0, 0, 0, 1, 0, 0,
      0, 0, 0, 0, 1, 0,
      0, 0, 0, 0, 0, 1]
  # n
  x0: [0, 0, 0, 0, 0, 0]
  #params: {number_of_elements_: 5}
  
  