isOnePersonToTrack: false

# front_cutted.bag
x_lower_limit: -2.6
x_upper_limit: 1.0
y_lower_limit: -1.0
y_upper_limit: 2.8

# four.bag
#x_lower_limit: -2.2
#x_upper_limit: 0.4
#y_lower_limit: -1.9
#y_upper_limit: 1.8

# drehen_two_persons.bag
#x_lower_limit: -1.0
#x_upper_limit: 1.0
#y_lower_limit: -1.0
#y_upper_limit: 1.0

# wand.bag
#x_lower_limit: -3.5
#x_upper_limit: 0.0
#y_lower_limit: 0.0
#y_upper_limit: 2.0

# one person
#x_lower_limit: -1.9
#x_upper_limit: -0.2
#y_lower_limit: -0.8
#y_upper_limit: 0.8

#actual limits
#x_lower_limit: -2.5
#x_upper_limit: 2.5
#y_lower_limit: -2.5
#y_upper_limit: 2.5

#extended limits
#x_lower_limit: -5.0
#x_upper_limit: 5.0
#y_lower_limit: -5.0
#y_upper_limit: 5.0



