scan_topic: /base_laser_rear/scan
transform_link: base_link
x_lower_limit: -2.6
x_upper_limit: 1.0
y_lower_limit: -1.0
y_upper_limit: 2.8
ransac_dist_threshold: 0.01
circle_fitting: centroid # ransac or centroid
leg_radius: 0.1
min_observations: 4
radius_of_person: 1.0
min_predictions: 7
z_coordinate: 0.178
vel_stance_threshold: 0.47
vel_swing_threshold: 0.93
